# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'PoC-Deploy-Azure-Policy'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'Deploy-Policies.ps1'
    arguments: '-Prefix "ZT" -Ring "ALL" -PoliciesFolder "$(System.DefaultWorkingDirectory)/aad_ca_templates/PolicySets/Category structure for AADP1"'