# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Set-PSRepository -InstallationPolicy Trusted -Name PSGallery
      Install-Module Microsoft.Graph -Force -Scope CurrentUser
    showWarnings: true
    pwsh: true
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'PoC-Deploy-Azure-Policy'
    ScriptType: 'FilePath'
    ScriptPath: 'Deploy-Policies.ps1'
    ScriptArguments: '-Prefix "CA" -Ring "ALL" -PoliciesFolder "$(System.DefaultWorkingDirectory)/aad_ca_templates/PolicySets/Category structure for AADP1"'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true