# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Default

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'PoC-Deploy-Azure-Policy'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'Deploy-Policies.ps1'
    arguments: '-Prefix "CA" -Ring "ALL" -PoliciesFolder "$(System.DefaultWorkingDirectory)\aad_ca_templates\PolicySets\Category structure for AADP1" -ClientId "$env:servicePrincipalId" -ClientSecret "$env:servicePrincipalKey" -TenantId "$env:tenantId"'
    addSpnToEnvironment: true