name: Deploy Azure Conditional Access Policies

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: non-prod-all
    steps:
      - run: git config --global core.longpaths true
      
      - uses: actions/checkout@v3

      - name: Deploy
        shell: pwsh
        run: |
          $azureCredentials = ConvertFrom-Json -InputObject '${{ secrets.AZURE_CREDENTIALS }}' -Depth 2
          .\Deploy-Policies.ps1 -Prefix '${{ vars.PREFIX }}' -Ring '${{ vars.RING }}' -PoliciesFolder '${{ github.workspace }}\aad_ca_templates\PolicySets\Category structure for AADP1' -ClientId "$($azureCredentials.clientId)" -ClientSecret "$($azureCredentials.clientSecret)" -TenantId "$($azureCredentials.tenantId)"
